### ISSUE TITLE
[BUG]파이어베이스 스토리지 에러

### ISSUE THREAD

**Issue by IAMISTP** [fcstudy-project/FastTime-front#56]
**문제 상황(자세히)**

```
const fetchImageUpload = async () => {
    const blob = await createBlob(imagePreview);
    const downloadUrl = await uploadImageToFirebase(blob);
    return downloadUrl;
  };


  const submitForm = (data: FetchDataType) => {
    try {
      const url = fetchImageUpload();
      console.log(url);
      console.log(data);
    } catch (error) {
      console.log(error);
    }
  };
```

문제 발생 : 이미지 첨부시 파이어베이스 스토리지에 이미지를 넣으려고 하였으나  Firebase 초기 설정에서 스토리지 버킷을 제대로 설정하지 않았을 때 발생하는 문제가 일어남

![Image](https://github.com/fcstudy-project/FastTime-front/assets/137421610/c573b98c-8ef8-45fe-963b-f7fb8fd77503)

**Comment by Gaoridang** [comment]
아무래도 ref 설정하신 거랑 실제 storage 주소가 달라서 그런거 같아요. 제가 hooks 폴더에 이미지 관련 코드 만들어둬서 fetchImageUpload로 새로 만들지 마시고 거기 있는거 사용하시면 될 거 같아요

**Comment by Gaoridang** [comment]
환경 변수 공유 문제
